apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-repo-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/maven/.m2/repository"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "maven-repo"
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
